"""add_status_to_follows

Revision ID: 13c55e5c6909
Revises: 7a1f9c2b4e8d
Create Date: 2026-07-12 02:05:17.146408+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '13c55e5c6909'
down_revision: str | None = '7a1f9c2b4e8d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('status', sa.String(length=20), server_default=sa.text("'accepted'"), nullable=False, comment='팔로우 상태 (pending | accepted)'))
    op.create_index(op.f('ix_follows_status'), 'follows', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follows_status'), table_name='follows')
    op.drop_column('follows', 'status')
    # ### end Alembic commands ###
