"""add email_verified to users

Revision ID: 98e3721d6e9a
Revises: 24bfca186a74
Create Date: 2026-07-07 08:58:31.432386+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e3721d6e9a'
down_revision: Union[str, None] = '24bfca186a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False, comment='이메일 인증 완료 여부 (local 가입자, 미인증 시 로그인 차단)'))
    # ### end Alembic commands ###
    # 기존 사용자(카카오 포함)는 모두 인증됨 처리 — 신규 가입자만 인증 절차
    op.execute('UPDATE users SET email_verified = true')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
