"""add media_status and original_media_url to climbing_logs

Revision ID: 57264df634d9
Revises: 35accf3ca108
Create Date: 2026-07-05 13:09:42.436171+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '57264df634d9'
down_revision: str | None = '35accf3ca108'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('climbing_logs', sa.Column('media_status', sa.String(length=20), nullable=True, comment='미디어 처리 상태 (processing | done | failed, null=이미지/없음)'))
    op.add_column('climbing_logs', sa.Column('original_media_url', sa.String(length=500), nullable=True, comment='원본 영상 URL (트랜스코딩 소스, 압축 후 삭제)'))
    op.alter_column('climbing_logs', 'media_url',
               existing_type=sa.VARCHAR(length=500),
               comment='미디어 URL (영상은 압축 완료 후 압축본, 이미지는 원본)',
               existing_comment='미디어 URL',
               existing_nullable=True)
    op.create_index(op.f('ix_climbing_logs_media_status'), 'climbing_logs', ['media_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_climbing_logs_media_status'), table_name='climbing_logs')
    op.alter_column('climbing_logs', 'media_url',
               existing_type=sa.VARCHAR(length=500),
               comment='미디어 URL',
               existing_comment='미디어 URL (영상은 압축 완료 후 압축본, 이미지는 원본)',
               existing_nullable=True)
    op.drop_column('climbing_logs', 'original_media_url')
    op.drop_column('climbing_logs', 'media_status')
    # ### end Alembic commands ###
