"""notifications climbing_log_id nullable

Revision ID: 24bfca186a74
Revises: c5cd9412990b
Create Date: 2026-07-06 08:27:27.895975+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '24bfca186a74'
down_revision: str | None = 'c5cd9412990b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'climbing_log_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='관련 게시물 (클릭 시 이동 대상)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'climbing_log_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='관련 게시물 (클릭 시 이동 대상)')
    # ### end Alembic commands ###
