"""add users table

Revision ID: c3f45b4553f4
Revises: 
Create Date: 2026-06-09 11:56:15.594664+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3f45b4553f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일 (카카오에서 받아옴)'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='닉네임 (사용자가 직접 설정)'),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True, comment='프로필 사진 URL'),
    sa.Column('bio', sa.String(length=500), nullable=True, comment='자기소개'),
    sa.Column('auth_provider', sa.String(length=20), nullable=False, comment='OAuth 프로바이더'),
    sa.Column('auth_provider_id', sa.String(length=255), nullable=False, comment='프로바이더의 사용자 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='가입 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='마지막 수정 시각'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='삭제 시각 (soft delete)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider', 'auth_provider_id', name='uq_users_oauth'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
