"""sync_schema_comments_and_indexes

Revision ID: 22d5a8accf04
Revises: df4bd125be8c
Create Date: 2026-07-03 15:42:49.867289+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22d5a8accf04'
down_revision: Union[str, None] = 'df4bd125be8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('climbing_logs', 'user_id',
               existing_type=sa.UUID(),
               comment='작성자 user id',
               existing_nullable=False)
    op.alter_column('climbing_logs', 'grade_raw',
               existing_type=sa.VARCHAR(length=50),
               comment='사용자가 본 그대로의 등급 (V3, 보라 등)',
               existing_nullable=False)
    op.alter_column('climbing_logs', 'grade_system',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='등급 표기 체계 (v_scale | color)',
               existing_nullable=False)
    op.alter_column('climbing_logs', 'gym_name',
               existing_type=sa.VARCHAR(length=100),
               comment='짐(암장) 이름 — 짐별 난이도 정규화 기반',
               existing_nullable=True)
    op.alter_column('climbing_logs', 'categories',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=30)),
               comment='문제 유형 다중 태그 (다이나믹, 슬랩 등)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('climbing_logs', 'comment',
               existing_type=sa.TEXT(),
               comment='코멘트 / 베타 메모',
               existing_nullable=True)
    op.alter_column('climbing_logs', 'attempts',
               existing_type=sa.INTEGER(),
               comment='시도 횟수',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('climbing_logs', 'is_success',
               existing_type=sa.BOOLEAN(),
               comment='완등(send) 성공 여부',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('climbing_logs', 'climbed_at',
               existing_type=sa.DATE(),
               comment='클라이밍 날짜 (기본 오늘)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('climbing_logs', 'media_type',
               existing_type=sa.VARCHAR(length=10),
               comment='미디어 유형 (video | image)',
               existing_nullable=True)
    op.alter_column('climbing_logs', 'media_url',
               existing_type=sa.VARCHAR(length=500),
               comment='미디어 URL',
               existing_nullable=True)
    op.alter_column('climbing_logs', 'visibility',
               existing_type=sa.VARCHAR(length=10),
               comment='공개 범위 (public | private)',
               existing_nullable=False,
               existing_server_default=sa.text("'public'::character varying"))
    op.alter_column('gym_grade_systems', 'gym_name',
               existing_type=sa.VARCHAR(length=100),
               comment='짐(암장) 이름 — climbing_logs.gym_name 과 매칭',
               existing_nullable=False)
    op.alter_column('gym_grade_systems', 'color_order',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=20)),
               comment='색 난이도 순서 (쉬운→어려운). 인덱스 = rank',
               existing_nullable=False)
    op.alter_column('gym_grade_systems', 'is_official',
               existing_type=sa.BOOLEAN(),
               comment='시스템 시드(true) / 사용자 등록(false)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('gym_grade_systems', 'created_by',
               existing_type=sa.UUID(),
               comment='사용자 등록 시 작성자 user id (시드는 NULL)',
               existing_nullable=True)
    op.drop_index(op.f('ix_gym_grade_systems_gym_name'), table_name='gym_grade_systems')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='이메일 (로그인 ID / 카카오에서 받아옴)',
               existing_comment='이메일 (카카오에서 받아옴)',
               existing_nullable=False)
    op.alter_column('users', 'auth_provider',
               existing_type=sa.VARCHAR(length=20),
               comment='인증 프로바이더 (local | kakao | google | apple)',
               existing_comment='OAuth 프로바이더',
               existing_nullable=False)
    op.alter_column('users', 'is_public',
               existing_type=sa.BOOLEAN(),
               comment='프로필 공개 여부 (Day 14)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_public',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='프로필 공개 여부 (Day 14)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'auth_provider',
               existing_type=sa.VARCHAR(length=20),
               comment='OAuth 프로바이더',
               existing_comment='인증 프로바이더 (local | kakao | google | apple)',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='이메일 (카카오에서 받아옴)',
               existing_comment='이메일 (로그인 ID / 카카오에서 받아옴)',
               existing_nullable=False)
    op.create_index(op.f('ix_gym_grade_systems_gym_name'), 'gym_grade_systems', ['gym_name'], unique=False)
    op.alter_column('gym_grade_systems', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='사용자 등록 시 작성자 user id (시드는 NULL)',
               existing_nullable=True)
    op.alter_column('gym_grade_systems', 'is_official',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='시스템 시드(true) / 사용자 등록(false)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('gym_grade_systems', 'color_order',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=20)),
               comment=None,
               existing_comment='색 난이도 순서 (쉬운→어려운). 인덱스 = rank',
               existing_nullable=False)
    op.alter_column('gym_grade_systems', 'gym_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='짐(암장) 이름 — climbing_logs.gym_name 과 매칭',
               existing_nullable=False)
    op.alter_column('climbing_logs', 'visibility',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='공개 범위 (public | private)',
               existing_nullable=False,
               existing_server_default=sa.text("'public'::character varying"))
    op.alter_column('climbing_logs', 'media_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='미디어 URL',
               existing_nullable=True)
    op.alter_column('climbing_logs', 'media_type',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='미디어 유형 (video | image)',
               existing_nullable=True)
    op.alter_column('climbing_logs', 'climbed_at',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='클라이밍 날짜 (기본 오늘)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('climbing_logs', 'is_success',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='완등(send) 성공 여부',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('climbing_logs', 'attempts',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='시도 횟수',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('climbing_logs', 'comment',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='코멘트 / 베타 메모',
               existing_nullable=True)
    op.alter_column('climbing_logs', 'categories',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=30)),
               comment=None,
               existing_comment='문제 유형 다중 태그 (다이나믹, 슬랩 등)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('climbing_logs', 'gym_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='짐(암장) 이름 — 짐별 난이도 정규화 기반',
               existing_nullable=True)
    op.alter_column('climbing_logs', 'grade_system',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'v_scale'::character varying"),
               comment=None,
               existing_comment='등급 표기 체계 (v_scale | color)',
               existing_nullable=False)
    op.alter_column('climbing_logs', 'grade_raw',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='사용자가 본 그대로의 등급 (V3, 보라 등)',
               existing_nullable=False)
    op.alter_column('climbing_logs', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='작성자 user id',
               existing_nullable=False)
    # ### end Alembic commands ###
