"""add notifications table

Revision ID: 35accf3ca108
Revises: 22d5a8accf04
Create Date: 2026-07-04 00:39:37.772443+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35accf3ca108'
down_revision: Union[str, None] = '22d5a8accf04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False, comment='알림 받는 사람 user id'),
    sa.Column('actor_id', sa.UUID(), nullable=False, comment='행동한 사람 user id (좋아요/댓글 단 사람)'),
    sa.Column('type', sa.String(length=30), nullable=False, comment='알림 유형 (post_like | post_comment | comment_reply)'),
    sa.Column('climbing_log_id', sa.UUID(), nullable=False, comment='관련 게시물 (클릭 시 이동 대상)'),
    sa.Column('comment_id', sa.UUID(), nullable=True, comment='관련 댓글 (댓글/대댓글 알림만)'),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='읽음 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['climbing_log_id'], ['climbing_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_recipient_created', 'notifications', ['recipient_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index('ix_notifications_recipient_created', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
